# Generated by Django 3.1.3 on 2020-12-02 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zolnierz',
            fields=[
                ('id_zolnierza', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('data_urodzenia', models.DateField()),
                ('telefon', models.CharField(max_length=15)),
                ('specjalnosc', models.CharField(max_length=90)),
                ('stanowisko_etatowe', models.CharField(max_length=90)),
                ('zameldowanie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wyjazdy_sluzbowe',
            fields=[
                ('id_wyjazdu', models.AutoField(primary_key=True, serialize=False)),
                ('miejsce_docelowe', models.CharField(max_length=45)),
                ('cel', models.CharField(max_length=45)),
                ('data_wyjazdu', models.DateField()),
                ('data_przyjazdu', models.DateField()),
                ('zolnierz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zolnierz')),
            ],
        ),
        migrations.CreateModel(
            name='Wnioski',
            fields=[
                ('id_wniosku', models.AutoField(primary_key=True, serialize=False)),
                ('rodzaj_wniosku', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('data_zlozenia', models.CharField(default=datetime.date.today, max_length=45)),
                ('zolnierz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zolnierz')),
            ],
        ),
        migrations.CreateModel(
            name='Przepustki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poczatek_przepustki', models.DateField()),
                ('koniec_przepustki', models.DateField()),
                ('zolnierz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zolnierz')),
            ],
        ),
        migrations.CreateModel(
            name='Kontrakty',
            fields=[
                ('id_kontraktu', models.AutoField(primary_key=True, serialize=False)),
                ('poczatek_kontraktu', models.DateField(default=datetime.date.today)),
                ('koniec_kontraktu', models.DateField()),
                ('wynagrodzenie', models.DecimalField(decimal_places=2, default=3200, max_digits=9)),
                ('zolnierz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zolnierz')),
            ],
        ),
        migrations.CreateModel(
            name='Ekwipunek',
            fields=[
                ('id_ekwipunku', models.AutoField(primary_key=True, serialize=False)),
                ('umundurowanie', models.CharField(max_length=45)),
                ('uzbrojenie', models.CharField(max_length=45)),
                ('oporzadzenie_uzbrojenia', models.CharField(max_length=45)),
                ('zolnierz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.zolnierz')),
            ],
        ),
    ]
